import type { PreviewStorefrontData } from "./types";

export const demoStorefrontData: PreviewStorefrontData = {
  store: {
    name: "Archive Room",
    logoText: "AR",
    announcement: "LIMITED DROP LIVE · RESERVE BEFORE IT'S GONE",
    heroTitle: "Curated streetwear drops, one piece at a time.",
    heroSubtitle:
      "Vintage jackets, cargos, tees and rare finds. Reserve your piece before it moves to WhatsApp.",
    story:
      "Archive Room releases small-batch vintage and streetwear edits with measured pieces, clear photos, and fast WhatsApp confirmation after booking.",
    socialProof: ["2.8k Instagram followers", "184 verified bookings", "4.9 buyer rating"],
    trustBadges: [
      "Verified booking",
      "Limited stock",
      "WhatsApp confirmation",
      "Seller reviews",
      "Secure checkout",
      "UPI accepted",
    ],
    collections: ["New Drop", "Jackets", "Denim", "Tees", "Accessories", "Under Rs. 999"],
  },
  products: [
    {
      id: "washed-denim-jacket",
      title: "Washed Denim Utility Jacket",
      price: 1299,
      compareAtPrice: 1899,
      imageUrl:
        "https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=900&q=80",
      galleryUrls: [
        "https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=1100&q=80",
        "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1100&q=80",
        "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=1100&q=80",
      ],
      collection: "Jackets",
      badge: "1 left",
      scarcity: "1 left",
      description: "Structured vintage denim jacket with a boxy streetwear fit, clean seams, and a soft washed handfeel.",
      sizes: ["S", "M", "L"],
      unavailableSizes: ["S"],
      colors: ["Denim"],
    },
    {
      id: "nylon-track-jacket",
      title: "Black Nylon Track Jacket",
      price: 1499,
      compareAtPrice: 2299,
      imageUrl:
        "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80",
      galleryUrls: [
        "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1100&q=80",
        "https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=1100&q=80",
      ],
      collection: "Jackets",
      badge: "New",
      scarcity: "1 left",
      description: "Lightweight nylon layer with contrast trims and a cropped vintage sportswear shape.",
      sizes: ["M", "L"],
      colors: ["Black"],
    },
    {
      id: "double-knee-denim",
      title: "Faded Double-Knee Denim",
      price: 1799,
      compareAtPrice: 2499,
      imageUrl:
        "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=80",
      collection: "Denim",
      badge: "Rare",
      scarcity: "1 left",
      description: "Heavy denim carpenter fit with worn-in fading, deep pockets, and a relaxed straight leg.",
      sizes: ["30", "32", "34"],
      colors: ["Washed denim"],
    },
    {
      id: "vintage-tee",
      title: "Vintage Racing Graphic Tee",
      price: 799,
      compareAtPrice: 1199,
      imageUrl:
        "https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=900&q=80",
      collection: "Tees",
      badge: "Under 999",
      scarcity: "1 left",
      description: "Soft washed graphic tee with vintage cracking and relaxed drape.",
      sizes: ["M", "L"],
      colors: ["Charcoal"],
    },
    {
      id: "mini-bag",
      title: "Glossy Mini Shoulder Bag",
      price: 999,
      compareAtPrice: 1399,
      imageUrl:
        "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80",
      collection: "Accessories",
      badge: "Drop pick",
      scarcity: "2 available",
      description: "Compact shoulder bag with glossy finish and enough room for daily carry.",
      sizes: ["One size"],
      colors: ["Black", "Wine"],
    },
    {
      id: "olive-cargo-pants",
      title: "Olive Parachute Cargo Pants",
      price: 1399,
      compareAtPrice: 1999,
      imageUrl:
        "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80",
      collection: "New Drop",
      badge: "1 left",
      scarcity: "1 left",
      description: "Roomy olive cargos with adjustable hems, clean hardware, and a streetwear silhouette.",
      sizes: ["S", "M", "L"],
      colors: ["Olive"],
    },
    {
      id: "cream-knit-polo",
      title: "Cream Knit Collar Polo",
      price: 999,
      compareAtPrice: 1499,
      imageUrl:
        "https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?auto=format&fit=crop&w=900&q=80",
      collection: "Under Rs. 999",
      badge: "New",
      scarcity: "2 available",
      description: "Soft knit polo with a relaxed collar, cropped length, and easy denim pairing.",
      sizes: ["S", "M"],
      colors: ["Ivory"],
    },
    {
      id: "silver-rings",
      title: "Stacked Silver Ring Set",
      price: 549,
      compareAtPrice: 799,
      imageUrl:
        "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=900&q=80",
      collection: "Accessories",
      badge: "Under 999",
      scarcity: "8 available",
      description: "Adjustable ring stack for everyday styling and creator looks.",
    },
    {
      id: "washed-flannel-shirt",
      title: "Washed Oversized Flannel",
      price: 1199,
      compareAtPrice: 1799,
      imageUrl:
        "https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?auto=format&fit=crop&w=900&q=80",
      collection: "New Drop",
      badge: "Rare",
      scarcity: "1 left",
      description: "Oversized flannel shirt with muted checks, soft brushed cotton, and a clean fall.",
      sizes: ["L", "XL"],
      colors: ["Brown check"],
    },
    {
      id: "logo-cap",
      title: "Washed Logo Cap",
      price: 699,
      compareAtPrice: 999,
      imageUrl:
        "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=80",
      collection: "Accessories",
      badge: "Under 999",
      scarcity: "3 available",
      description: "Washed cotton cap with a low profile, curved brim, and faded embroidered mark.",
      sizes: ["Adjustable"],
      colors: ["Washed black"],
    },
  ],
  testimonials: [
    {
      quote: "Booked in 20 seconds and seller confirmed everything on WhatsApp.",
      name: "Aarohi",
      meta: "Verified buyer",
      rating: 5,
      dateTag: "May drop",
    },
    {
      quote: "Photos were accurate, packaging was clean, and delivery was smooth.",
      name: "Riya",
      meta: "Repeat buyer",
      rating: 5,
      dateTag: "Last week",
    },
    {
      quote: "Felt much more legit than sending money to a random DM.",
      name: "Kabir",
      meta: "First-time buyer",
      rating: 4,
      dateTag: "Weekend drop",
    },
  ],
  faqs: [
    {
      question: "Does this preview place real orders?",
      answer: "No. Product actions on this internal preview open a mock detail panel only.",
    },
    {
      question: "How does PayPerTap booking work?",
      answer: "Buyers pay Rs. 20 to reserve an item, then continue on WhatsApp with the seller.",
    },
    {
      question: "Can sellers edit these themes later?",
      answer: "Later phases can add safe form-based controls without raw HTML or CSS editing.",
    },
  ],
};
