import { expect, test } from "@playwright/test";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

const baseUrl = process.env.SMOKE_BASE_URL || "https://www.paypertap.in";
const runFullE2E = process.env.RUN_FULL_E2E === "1";

test.skip(!runFullE2E, "Set RUN_FULL_E2E=1 to create real Firebase smoke data.");
test.use({ channel: "chrome" });

test("seller can onboard and buyer can complete a demo booking", async ({ page }) => {
  const stamp = Date.now();
  const email = `paypertap-smoke-${stamp}@paypertap.in`;
  const password = `Smoke${stamp}!`;
  const storeName = `Smoke Store ${stamp}`;
  const storeSlug = `smoke-store-${stamp}`;
  const productTitle = `Smoke Product ${stamp}`;
  const imagePath = join(tmpdir(), `paypertap-smoke-${stamp}.png`);
  const tinyPng = Buffer.from(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=",
    "base64",
  );
  const pageErrors: string[] = [];

  writeFileSync(imagePath, tinyPng);
  page.on("pageerror", (error) => pageErrors.push(error.message));

  await page.goto(`${baseUrl}/auth`);
  await page.getByPlaceholder("you@example.com").fill(email);
  await page.getByPlaceholder("Minimum 6 characters").fill(password);
  await page.getByRole("button", { name: "Continue with Email" }).click();

  await expect(page).toHaveURL(/\/onboarding\/store/, { timeout: 30000 });
  await page.getByLabel("Phone number").fill("9876543210");
  await page.getByLabel("Store name").fill(storeName);
  await page.locator('input[type="file"]').setInputFiles(imagePath);
  await page.getByRole("button", { name: "Continue" }).click();

  await expect(page).toHaveURL(/\/onboarding\/product/, { timeout: 30000 });
  await page.getByLabel("Product title").fill(productTitle);
  await page.getByLabel("Price").fill("499");
  await page.getByLabel("Category").fill("Smoke");
  await page.getByLabel("Inventory quantity").fill("3");
  await page.getByLabel("Description").fill("Generated by PayPerTap launch smoke test.");
  await page.locator('input[type="file"]').setInputFiles(imagePath);
  await page.getByRole("button", { name: "Save product and continue" }).click();

  await expect(page).toHaveURL(/\/dashboard/, { timeout: 45000 });
  await expect(page.getByText(storeName)).toBeVisible({ timeout: 30000 });
  await page.getByRole("button", { name: "Products" }).click();
  await expect(page.getByText(productTitle).first()).toBeVisible({ timeout: 30000 });

  await page.goto(`${baseUrl}/${storeSlug}`);
  await expect(page.getByText(storeName)).toBeVisible({ timeout: 30000 });
  await expect(page.getByText(productTitle)).toBeVisible({ timeout: 30000 });

  await page.getByText(productTitle).click();
  await expect(page).toHaveURL(new RegExp(`/${storeSlug}/product/`), {
    timeout: 30000,
  });
  await expect(page.getByRole("heading", { name: productTitle })).toBeVisible({
    timeout: 30000,
  });
  await page.getByRole("link", { name: /Book for/ }).click();

  await expect(page).toHaveURL(new RegExp(`/${storeSlug}/checkout/`), {
    timeout: 30000,
  });
  await page.getByLabel("Name").fill("Smoke Buyer");
  await page.getByLabel("Phone").fill("9876500000");
  await page.getByLabel("Address").fill("Smoke address");
  await page.getByLabel("City").fill("Bengaluru");
  await page.getByLabel("Pincode").fill("560001");
  await page.getByRole("button", { name: "Continue" }).click();
  await page.getByRole("button", { name: /Pay .* reserve/ }).click();

  await expect(page).toHaveURL(new RegExp(`/${storeSlug}/booking-success/`), {
    timeout: 45000,
  });
  await expect(page.getByText("Your item is reserved.")).toBeVisible({
    timeout: 30000,
  });
  expect(pageErrors).toEqual([]);
});
